// test_programs.c: whole-program runs through dsd_game_boot on the host platform, compared with goldens:
//   - conformance tiers: only the DSD|LOG| lines, against fixtures/conformance/expected/** (contract C6), for WS2's
//     hand-assembled programs and for WS4's compiler output (fixtures/compiler/conformance, reached by merging WS4);
//   - runtime fixtures (fixtures/bytecode/*.out, fixtures/bytecode/runtime/*.out): the full output, READY and
//     EXIT/ERR included, so error codes, object/event/file/line and messages are pinned.
#include <stdio.h>
#include <string.h>

#include "game.h"
#include "host.h"
#include "test.h"

// Captured protocol output of one run.
#define CAPTURE_MAX (256 * 1024)
#define EXPECT_MAX (256 * 1024)
#define TRACE_MAX (1024 * 1024) // a 600-frame trace (~210 KB for Flappy)
#define LOG_PREFIX "DSD|LOG|"
#define RUN_SEED 1u // every run passes a seed (CLAUDE.md: always --seed N)

static char g_capture[CAPTURE_MAX];
static uint32_t g_capture_len;
static char g_expected[EXPECT_MAX];
static char g_filtered[CAPTURE_MAX];

// HostLogSink: appends each line to g_capture.
static void capture(const char *line, uint32_t len, void *ctx) {
    (void)ctx;
    if (g_capture_len + len >= CAPTURE_MAX) return;
    memcpy(g_capture + g_capture_len, line, len);
    g_capture_len += len;
    g_capture[g_capture_len] = '\0';
}

// Key script of the running case (static: the host keeps a pointer to it).
static HostKeyScript g_keys;
static char g_key_text[EXPECT_MAX];

// Boots one program with output captured, runs up to `frames` frames with the key script `keys` (or none), and
// returns the game state.
static int32_t run_frames(const char *root, uint32_t frames, const char *keys) {
    g_capture_len = 0;
    g_capture[0] = '\0';
    const HostKeyScript *ks = NULL;
    if (keys != NULL) {
        char err[HOST_KEY_ERR_MAX];
        int32_t n = dsd_test_read_file(keys, g_key_text, sizeof g_key_text);
        if (!CHECK(n >= 0) || !CHECK(host_keys_parse(&g_keys, g_key_text, (uint32_t)n, err, sizeof err))) return -1;
        ks = &g_keys;
    }
    HostConfig cfg = {root, RUN_SEED, ks, capture, NULL};
    host_configure(&cfg);
    int32_t st = dsd_game_boot();
    for (uint32_t f = 0; f < frames && st == DSD_GAME_RUNNING; f++) st = dsd_game_frame();
    return st;
}

static int32_t run_program(const char *root) { return run_frames(root, 0, NULL); }

// Keeps only the lines of `text` that start with `prefix`, into out.
static void keep_lines(const char *text, const char *prefix, char *out, uint32_t cap) {
    uint32_t n = 0;
    size_t plen = strlen(prefix);
    while (*text != '\0') {
        const char *nl = strchr(text, '\n');
        size_t len = nl ? (size_t)(nl - text) + 1 : strlen(text);
        if (strncmp(text, prefix, plen) == 0 && n + len < cap) {
            memcpy(out + n, text, len);
            n += (uint32_t)len;
        }
        text += len;
    }
    out[n] = '\0';
}

// Reads an expected-output file with '\r' removed (goldens compare after stripping \r).
static bool read_expected(const char *path) {
    int32_t n = dsd_test_read_file(path, g_expected, EXPECT_MAX - 1);
    if (!CHECK(n >= 0)) return false;
    uint32_t w = 0;
    for (int32_t i = 0; i < n; i++) {
        if (g_expected[i] != '\r') g_expected[w++] = g_expected[i];
    }
    g_expected[w] = '\0';
    return true;
}

// One program and its golden.
typedef struct ProgramCase {
    const char *dsdb;
    const char *expected;
    bool log_only;     // compare only DSD|LOG| lines (conformance goldens)
    int32_t state;     // the final state: DSD_GAME_EXITED, DSD_GAME_FAILED, or DSD_GAME_RUNNING after `frames`
    uint32_t frames;   // frames to run a room game for (--frames); 0 for program form
    const char *keys;  // key script (--input), or NULL
} ProgramCase;

static const ProgramCase CASES[] = {
    {"fixtures/bytecode/hello.dsdb", "fixtures/bytecode/hello.out", false, DSD_GAME_EXITED, 0, NULL},
    {"fixtures/bytecode/conformance/v0-01.dsdb", "fixtures/conformance/expected/v0/01-arith.log", true,
     DSD_GAME_EXITED, 0, NULL},
    {"fixtures/bytecode/conformance/v0-02.dsdb", "fixtures/conformance/expected/v0/02-fixed.log", true,
     DSD_GAME_EXITED, 0, NULL},
    {"fixtures/bytecode/conformance/v0-03.dsdb", "fixtures/conformance/expected/v0/03-compare.log", true,
     DSD_GAME_EXITED, 0, NULL},
    {"fixtures/bytecode/conformance/v0-04.dsdb", "fixtures/conformance/expected/v0/04-control.log", true,
     DSD_GAME_EXITED, 0, NULL},
    {"fixtures/bytecode/conformance/v0-05.dsdb", "fixtures/conformance/expected/v0/05-functions.log", true,
     DSD_GAME_EXITED, 0, NULL},
    // WS4's compiler output for the same programs (fixtures/compiler, regenerated by WS4): compiler + runtime.
    {"fixtures/compiler/conformance/v0/01-arith.dsdb", "fixtures/conformance/expected/v0/01-arith.log", true,
     DSD_GAME_EXITED, 0, NULL},
    {"fixtures/compiler/conformance/v0/02-fixed.dsdb", "fixtures/conformance/expected/v0/02-fixed.log", true,
     DSD_GAME_EXITED, 0, NULL},
    {"fixtures/compiler/conformance/v0/03-compare.dsdb", "fixtures/conformance/expected/v0/03-compare.log", true,
     DSD_GAME_EXITED, 0, NULL},
    {"fixtures/compiler/conformance/v0/04-control.dsdb", "fixtures/conformance/expected/v0/04-control.log", true,
     DSD_GAME_EXITED, 0, NULL},
    {"fixtures/compiler/conformance/v0/05-functions.dsdb", "fixtures/conformance/expected/v0/05-functions.log",
     true, DSD_GAME_EXITED, 0, NULL},
    // Tier v1 (strings and arrays), hand-assembled by WS2 until WS4's programs 6-10 land.
    {"fixtures/bytecode/v1-01-strings.dsdb", "fixtures/bytecode/v1-01-strings.out", false, DSD_GAME_EXITED, 0, NULL},
    {"fixtures/bytecode/v1-02-arrays.dsdb", "fixtures/bytecode/v1-02-arrays.out", false, DSD_GAME_EXITED, 0, NULL},
    {"fixtures/bytecode/v1-03-collector.dsdb", "fixtures/bytecode/v1-03-collector.out", false, DSD_GAME_EXITED, 0, NULL},
    {"fixtures/bytecode/runtime/err-index.dsdb", "fixtures/bytecode/runtime/err-index.out", false, DSD_GAME_FAILED, 0, NULL},
    {"fixtures/bytecode/runtime/err-not-a-list.dsdb", "fixtures/bytecode/runtime/err-not-a-list.out", false,
     DSD_GAME_FAILED, 0, NULL},
    // Tier v2 (instances and events), hand-assembled room games: full output after the given frames.
    {"fixtures/bytecode/v2-01-lifecycle.dsdb", "fixtures/bytecode/v2-01-lifecycle.out", false, DSD_GAME_RUNNING, 3, NULL},
    {"fixtures/bytecode/v2-02-with.dsdb", "fixtures/bytecode/v2-02-with.out", false, DSD_GAME_RUNNING, 1, NULL},
    {"fixtures/bytecode/v2-03-rooms.dsdb", "fixtures/bytecode/v2-03-rooms.out", false, DSD_GAME_RUNNING, 3, NULL},
    {"fixtures/bytecode/v2-04-end.dsdb", "fixtures/bytecode/v2-04-end.out", false, DSD_GAME_EXITED, 5, NULL},
    {"fixtures/bytecode/v2-05-input.dsdb", "fixtures/bytecode/v2-05-input.out", false, DSD_GAME_RUNNING, 10,
     "fixtures/bytecode/v2-05-input.keys"},
    {"fixtures/bytecode/v2-06-motion.dsdb", "fixtures/bytecode/v2-06-motion.out", false, DSD_GAME_RUNNING, 3, NULL},
    // Tier v3 (collisions, places, animation, Outside Room, touch), room games with SPRG sprite geometry.
    {"fixtures/bytecode/v3-01-collide.dsdb", "fixtures/bytecode/v3-01-collide.out", false, DSD_GAME_RUNNING, 15, NULL},
    {"fixtures/bytecode/v3-02-anim-outside-touch.dsdb", "fixtures/bytecode/v3-02-anim-outside-touch.out", false,
     DSD_GAME_RUNNING, 10, "fixtures/bytecode/v3-02-anim-outside-touch.keys"},
    {"fixtures/bytecode/bench.dsdb", "fixtures/bytecode/bench.out", false, DSD_GAME_RUNNING, 2, NULL},
    {"fixtures/bytecode/runtime/err-unset-slot.dsdb", "fixtures/bytecode/runtime/err-unset-slot.out", false,
     DSD_GAME_FAILED, 2, NULL},
    {"fixtures/bytecode/runtime/cmpj.dsdb", "fixtures/bytecode/runtime/cmpj.out", false, DSD_GAME_EXITED, 0, NULL},
    {"fixtures/bytecode/runtime/strings.dsdb", "fixtures/bytecode/runtime/strings.out", false, DSD_GAME_EXITED, 0, NULL},
    {"fixtures/bytecode/runtime/err-assert.dsdb", "fixtures/bytecode/runtime/err-assert.out", false,
     DSD_GAME_FAILED, 0, NULL},
    {"fixtures/bytecode/runtime/err-compare.dsdb", "fixtures/bytecode/runtime/err-compare.out", false,
     DSD_GAME_FAILED, 0, NULL},
    {"fixtures/bytecode/runtime/err-divzero.dsdb", "fixtures/bytecode/runtime/err-divzero.out", false,
     DSD_GAME_FAILED, 0, NULL},
    {"fixtures/bytecode/runtime/err-missing-builtin.dsdb", "fixtures/bytecode/runtime/err-missing-builtin.out", false,
     DSD_GAME_FAILED, 0, NULL},
    {"fixtures/bytecode/runtime/err-overflow.dsdb", "fixtures/bytecode/runtime/err-overflow.out", false,
     DSD_GAME_FAILED, 0, NULL},
    {"fixtures/bytecode/runtime/err-recursion.dsdb", "fixtures/bytecode/runtime/err-recursion.out", false,
     DSD_GAME_FAILED, 0, NULL},
    {"fixtures/bytecode/runtime/err-string-plus-number.dsdb", "fixtures/bytecode/runtime/err-string-plus-number.out",
     false, DSD_GAME_FAILED, 0, NULL},
    {"fixtures/bytecode/runtime/err-unset-global.dsdb", "fixtures/bytecode/runtime/err-unset-global.out", false,
     DSD_GAME_FAILED, 0, NULL},
    {"fixtures/bytecode/runtime/err-watchdog.dsdb", "fixtures/bytecode/runtime/err-watchdog.out", false,
     DSD_GAME_FAILED, 0, NULL},
};

static void test_cases(void) {
    for (size_t i = 0; i < sizeof CASES / sizeof CASES[0]; i++) {
        const ProgramCase *c = &CASES[i];
        int32_t st = run_frames(c->dsdb, c->frames, c->keys);
        if (!dsd_test_check_i64(st, c->state, __FILE__, __LINE__, c->dsdb)) continue;
        dsd_test_check_i64(host_fatal_seen(), c->state == DSD_GAME_FAILED, __FILE__, __LINE__, c->dsdb);
        if (!read_expected(c->expected)) continue;
        if (c->log_only) {
            keep_lines(g_capture, LOG_PREFIX, g_filtered, sizeof g_filtered);
            dsd_test_check_str(g_filtered, g_expected, __FILE__, __LINE__, c->dsdb);
        } else {
            dsd_test_check_str(g_capture, g_expected, __FILE__, __LINE__, c->dsdb);
        }
    }
}

static void test_missing_file(void) {
    CHECK_EQ(run_program("fixtures/bytecode/no-such-game.dsdb"), DSD_GAME_FAILED);
    CHECK_STR(g_capture, "DSD|ERR|R584|||game.dsdb|0|The game file could not be read (game.dsdb)\n");
    CHECK(host_fatal_seen());
}

static void test_core_main(void) {
    // C11 0.2.0: the DS entry point runs the whole game; 0 after DSD|EXIT, 1 after DSD|ERR.
    HostConfig cfg = {"fixtures/bytecode/hello.dsdb", RUN_SEED, NULL, capture, NULL};
    g_capture_len = 0;
    host_configure(&cfg);
    CHECK_EQ(dsd_core_main(), 0);
    CHECK_STR(g_capture, "DSD|READY|0.1.0|0dd9987a\nDSD|LOG|hello\nDSD|EXIT|0\n");
    // No file system (the host's dsd_plat_init fails without a root): R584, and dsd_core_main returns 1.
    HostConfig none = {NULL, RUN_SEED, NULL, capture, NULL};
    g_capture_len = 0;
    g_capture[0] = '\0';
    host_configure(&none);
    CHECK_EQ(dsd_core_main(), 1);
    CHECK_STR(g_capture, "DSD|ERR|R584|||game.dsdb|0|The game file could not be read (file system)\n");
}

static void test_repeatable(void) {
    // Booting again resets every piece of state: the second run prints the same bytes.
    static char first[CAPTURE_MAX];
    run_program("fixtures/bytecode/conformance/v0-05.dsdb");
    memcpy(first, g_capture, g_capture_len + 1);
    run_program("fixtures/bytecode/conformance/v0-05.dsdb");
    CHECK_STR(g_capture, first);
}

static void test_collector_ran(void) {
    // v1-03 makes ~2.3 MB of short-lived text in a 192 KB arena: the collector must have run, and the output (checked
    // in test_cases) shows the live list survived it.
    run_program("fixtures/bytecode/v1-03-collector.dsdb");
    CHECK(dsd_game_vm()->heap.collections > 0);
}

// Runs a room game for `frames` frames writing its --trace to `path` (under runtime/build-host/, which exists
// whenever the tests run). False when the trace could not be written.
static bool trace_run(const char *dsdb, uint32_t frames, const char *keys, const char *path) {
    FILE *f = fopen(path, "wb");
    if (f == NULL) return false;
    g_capture_len = 0;
    char err[HOST_KEY_ERR_MAX];
    int32_t n = dsd_test_read_file(keys, g_key_text, sizeof g_key_text);
    bool ok = n >= 0 && host_keys_parse(&g_keys, g_key_text, (uint32_t)n, err, sizeof err);
    HostConfig cfg = {dsdb, RUN_SEED, &g_keys, capture, NULL};
    host_configure(&cfg);
    int32_t st = dsd_game_boot();
    for (uint32_t fr = 0; ok && fr < frames && st == DSD_GAME_RUNNING; fr++) {
        st = dsd_game_frame();
        ok = st != DSD_GAME_FAILED && host_trace_frame(f, fr);
    }
    return fclose(f) == 0 && ok;
}

// FNV-1a 32 of n bytes (the same hash C2 uses for the ABI hash).
static uint32_t fnv1a(const char *p, int32_t n) {
    uint32_t h = 0x811C9DC5u;
    for (int32_t i = 0; i < n; i++) {
        h ^= (uint8_t)p[i];
        h *= 0x01000193u;
    }
    return h;
}

static void test_flappy_deterministic(void) {
    // The DoD run on the host: WS4's compiled Flappy, 600 frames, the DoD key script. Two runs must trace
    // identically, and while flappy.dsdb is the one the fingerprints were made from, the trace must match them: the
    // Linux and MinGW builds then agree byte for byte (the DoD's cross-compiler identity check).
    static char a[TRACE_MAX];
    static char b[TRACE_MAX];
    static char dsdb_bytes[EXPECT_MAX];
    const char *dsdb = "fixtures/compiler/samples/flappy.dsdb";
    const char *keys = "fixtures/runtime-core/flappy-keys.txt";
    if (!CHECK(trace_run(dsdb, 600, keys, "runtime/build-host/flappy-a.jsonl"))) return;
    if (!CHECK(trace_run(dsdb, 600, keys, "runtime/build-host/flappy-b.jsonl"))) return;
    int32_t na = dsd_test_read_file("runtime/build-host/flappy-a.jsonl", a, TRACE_MAX);
    int32_t nb = dsd_test_read_file("runtime/build-host/flappy-b.jsonl", b, TRACE_MAX);
    CHECK(na > 0 && na == nb && memcmp(a, b, (size_t)na) == 0);
    // Fingerprints: "dsdb 0x........" and "trace 0x........ <bytes>".
    char want[EXPECT_MAX];
    int32_t nw = dsd_test_read_file("fixtures/runtime-core/flappy-trace.fnv", want, EXPECT_MAX - 1);
    int32_t nd = dsd_test_read_file(dsdb, dsdb_bytes, EXPECT_MAX);
    if (!CHECK(nw > 0 && nd > 0)) return;
    want[nw] = '\0';
    char got[EXPECT_MAX];
    snprintf(got, sizeof got, "dsdb 0x%08x\ntrace 0x%08x %d\n", (unsigned)fnv1a(dsdb_bytes, nd), (unsigned)fnv1a(a, na),
             (int)na);
    if (strncmp(got, want, strlen("dsdb 0x00000000")) != 0) {
        printf("note: %s changed since fixtures/runtime-core/flappy-trace.fnv was made; the trace check is skipped.\n"
               "      Regenerate it (fixtures/runtime-core/README.md); the new fingerprints are:\n%s",
               dsdb, got);
        return;
    }
    if (!CHECK_STR(got, want)) printf("      the trace is runtime/build-host/flappy-a.jsonl\n");
}

void suite_programs(void) {
    test_cases();
    test_collector_ran();
    test_flappy_deterministic();
    test_missing_file();
    test_core_main();
    test_repeatable();
}
