// gen_font.mjs: writes runtime/host/font8x8.h, the host renderer's copy of the UI font runtime/data/font8x8.bin
// (WS3's file, linked into arm9.elf by the DS build). Run from the repo root after the .bin changes:
//     node runtime/host/gen_font.mjs
// The host tests compare the header with the .bin byte for byte, so a stale copy fails `make test`.
import { readFileSync, writeFileSync } from "node:fs";

const SOURCE = "runtime/data/font8x8.bin";
const TARGET = "runtime/host/font8x8.h";
const BYTES_PER_LINE = 16; // array bytes per source line

const bin = readFileSync(SOURCE);
const lines = [];
for (let i = 0; i < bin.length; i += BYTES_PER_LINE) {
  const row = [...bin.subarray(i, i + BYTES_PER_LINE)].map((b) => `0x${b.toString(16).padStart(2, "0")}`);
  lines.push(`    ${row.join(", ")},`);
}
const text = `// font8x8.h: generated by runtime/host/gen_font.mjs from ${SOURCE}. Do not edit.
// The UI layer's 8x8 font (libnds's default console font, zlib licence; see runtime/data/README.md): 96 glyphs for
// ASCII 0x20-0x7F, 8 bytes each (one per row, top to bottom), bit 0 the leftmost pixel.
#ifndef DSD_HOST_FONT8X8_H
#define DSD_HOST_FONT8X8_H

#include <stdint.h>

#define HOST_FONT_BYTES ${bin.length}u

static const uint8_t HOST_FONT8X8[HOST_FONT_BYTES] = {
${lines.join("\n")}
};

#endif // DSD_HOST_FONT8X8_H
`;
writeFileSync(TARGET, text);
