// Generates, from contracts/builtins.json (C2):
//   runtime/gen/builtins_table.h                    (the runtime's X-macro tables and ABI hash)
//   packages/compiler/src/gen/builtins.ts           (signatures for the checker and codegen)
//   packages/language-service/src/gen/builtins.ts   (signatures plus doc/example for completion and hover)
// Usage: node tools/gen-builtins.ts [--check]
import { abiHash, type BuiltinEntry, type BuiltinsFile, hex32 } from "@dsdude/dsdb";
import { emit, readJson } from "./lib/gen.ts";

interface Entry extends BuiltinEntry {
  category: string;
  doc: string;
  example: string;
  allowedEvents?: "*" | string[];
  pure?: boolean;
  readonly?: boolean;
  arrayLength?: number;
  since: string;
  aliasOf?: string;
  argMap?: number[];
  note?: string;
  match?: "exact" | "prefix";
  message?: string;
  manual?: string;
}

const HEADER = "Generated by tools/gen-builtins.ts from contracts/builtins.json. Do not edit.";

export function render(file: BuiltinsFile & { entries: Entry[] }): { h: string; compiler: string; ls: string } {
  const hash = abiHash(file.entries);
  const byId = [...file.entries].sort((a, b) => a.id - b.id);
  const fns = byId.filter((e) => e.kind === "function");
  const vars = byId.filter((e) => e.kind === "variable");
  const consts = byId.filter((e) => e.kind === "constant");
  // Compiler/language-service only: aliases and unsupported names never reach the runtime or the ABI hash.
  const aliases = byId.filter((e) => e.kind === "alias");
  const unsupported = byId.filter((e) => e.kind === "unsupported");
  const xlist = (name: string, rows: string[]) => [
    `#define ${name}(X) \\`,
    ...rows.map((r, i) => `  ${r}${i < rows.length - 1 ? " \\" : ""}`),
  ];
  const h = [
    `/* ${HEADER} */`,
    "#ifndef DSD_GEN_BUILTINS_TABLE_H",
    "#define DSD_GEN_BUILTINS_TABLE_H",
    "",
    `#define DSD_BUILTINS_VERSION "${file.version}"`,
    `#define DSD_ABI_HASH 0x${hex32(hash)}u`,
    `#define DSD_BUILTIN_FUNC_COUNT ${fns.length}`,
    `#define DSD_BUILTIN_VAR_COUNT ${vars.length}`,
    `#define DSD_BUILTIN_CONST_COUNT ${consts.length}`,
    "",
    "/* X(index, name, minArgs, maxArgs, pure): index is the dense runtime index, CALLN's C operand. */",
    ...xlist(
      "DSD_BUILTIN_FUNCS",
      fns.map((e, i) => `X(${i}, ${e.name}, ${e.minArgs}, ${e.maxArgs}, ${e.pure ? 1 : 0})`),
    ),
    "",
    "/* X(index, name, global, readonly, arrayLength): index is the dense variable index (GETBI/SETBI, provisional). */",
    ...xlist(
      "DSD_BUILTIN_VARS",
      vars.map(
        (e, i) => `X(${i}, ${e.name}, ${e.scope === "global" ? 1 : 0}, ${e.readonly ? 1 : 0}, ${e.arrayLength ?? 0})`,
      ),
    ),
    "",
    "/* X(name, value) */",
    ...xlist(
      "DSD_BUILTIN_CONSTS",
      consts.map((e) => `X(${e.name}, ${e.value})`),
    ),
    "",
    "#endif",
    "",
  ].join("\n");

  const j = (v: unknown) => JSON.stringify(v);
  const common = [
    `export const BUILTINS_VERSION = "${file.version}";`,
    `/** contracts/dsdb.md "ABI hash"; stamped into every DSDB header. */`,
    `export const ABI_HASH = 0x${hex32(hash)};`,
    "",
    "export interface BuiltinParam {",
    "  readonly name: string;",
    "  readonly type: string;",
    "  /** DSS expression used when the argument is left out. */",
    "  readonly default?: string;",
    "}",
    "",
  ];
  const fnLine = (e: Entry, i: number, docs: boolean) =>
    `  { id: ${e.id}, name: ${j(e.name)}, runtimeIndex: ${i}, params: ${j(e.params)}, minArgs: ${e.minArgs}, maxArgs: ${e.maxArgs}, returns: ${j(e.returns)}, allowedEvents: ${j(e.allowedEvents)}, pure: ${e.pure}${docs ? `, category: ${j(e.category)}, doc: ${j(e.doc)}, example: ${j(e.example)}` : ""} },`;
  const varLine = (e: Entry, i: number, docs: boolean) =>
    `  { id: ${e.id}, name: ${j(e.name)}, runtimeIndex: ${i}, scope: ${j(e.scope)}, type: ${j(e.type)}, readonly: ${e.readonly}, arrayLength: ${e.arrayLength}${docs ? `, category: ${j(e.category)}, doc: ${j(e.doc)}, example: ${j(e.example)}` : ""} },`;
  const constLine = (e: Entry, docs: boolean) =>
    `  { id: ${e.id}, name: ${j(e.name)}, type: ${j(e.type)}, value: ${e.value}${docs ? `, category: ${j(e.category)}, doc: ${j(e.doc)}, example: ${j(e.example)}` : ""} },`;
  const docFields = (docs: boolean) =>
    docs ? ["  readonly category: string;", "  readonly doc: string;", "  readonly example: string;"] : [];
  const body = (docs: boolean) => [
    `// ${HEADER}`,
    "",
    ...common,
    "export interface BuiltinFunction {",
    "  readonly id: number;",
    "  readonly name: string;",
    "  /** Dense runtime index: CALLN's C operand. */",
    "  readonly runtimeIndex: number;",
    "  readonly params: readonly BuiltinParam[];",
    "  readonly minArgs: number;",
    "  readonly maxArgs: number;",
    "  readonly returns: string;",
    '  /** "*" or the event file stems where the call is allowed. */',
    '  readonly allowedEvents: "*" | readonly string[];',
    "  readonly pure: boolean;",
    ...docFields(docs),
    "}",
    "",
    "export interface BuiltinVariable {",
    "  readonly id: number;",
    "  readonly name: string;",
    "  readonly runtimeIndex: number;",
    '  readonly scope: "instance" | "global";',
    "  readonly type: string;",
    "  readonly readonly: boolean;",
    "  /** 0 for a plain variable; alarm is 8, view_x/view_y are 2. */",
    "  readonly arrayLength: number;",
    ...docFields(docs),
    "}",
    "",
    "export interface BuiltinConstant {",
    "  readonly id: number;",
    "  readonly name: string;",
    "  readonly type: string;",
    "  readonly value: number;",
    ...docFields(docs),
    "}",
    "",
    "export const BUILTIN_FUNCTIONS: readonly BuiltinFunction[] = [",
    ...fns.map((e, i) => fnLine(e, i, docs)),
    "];",
    "",
    "export const BUILTIN_VARIABLES: readonly BuiltinVariable[] = [",
    ...vars.map((e, i) => varLine(e, i, docs)),
    "];",
    "",
    "export const BUILTIN_CONSTANTS: readonly BuiltinConstant[] = [",
    ...consts.map((e) => constLine(e, docs)),
    "];",
    "",
    "/** A GameMaker name compiled as `aliasOf` with a W lint (`note`); `argMap` lists the arguments passed on. */",
    "export interface BuiltinAlias {",
    "  readonly id: number;",
    "  readonly name: string;",
    "  readonly aliasOf: string;",
    "  readonly argMap?: readonly number[];",
    "  readonly note: string;",
    ...docFields(docs),
    "}",
    "",
    "/** A GameMaker name DSDude 0.1 lacks: E207 with `message`, linking `manual`. `prefix` matches names starting with `name` minus its `*`. */",
    "export interface BuiltinUnsupported {",
    "  readonly id: number;",
    "  readonly name: string;",
    '  readonly match: "exact" | "prefix";',
    "  readonly message: string;",
    "  readonly manual: string;",
    "}",
    "",
    "export const BUILTIN_ALIASES: readonly BuiltinAlias[] = [",
    ...aliases.map(
      (e) =>
        `  { id: ${e.id}, name: ${j(e.name)}, aliasOf: ${j(e.aliasOf)}${e.argMap ? `, argMap: ${j(e.argMap)}` : ""}, note: ${j(e.note)}${docs ? `, category: ${j(e.category)}, doc: ${j(e.doc)}, example: ${j(e.example)}` : ""} },`,
    ),
    "];",
    "",
    "export const BUILTIN_UNSUPPORTED: readonly BuiltinUnsupported[] = [",
    ...unsupported.map(
      (e) =>
        `  { id: ${e.id}, name: ${j(e.name)}, match: ${j(e.match)}, message: ${j(e.message)}, manual: ${j(e.manual)} },`,
    ),
    "];",
    "",
  ];
  return { h, compiler: body(false).join("\n"), ls: body(true).join("\n") };
}

if (import.meta.main) {
  const { h, compiler, ls } = render(readJson("contracts/builtins.json"));
  process.exit(
    emit(
      "gen-builtins",
      [
        { path: "runtime/gen/builtins_table.h", content: h },
        { path: "packages/compiler/src/gen/builtins.ts", content: compiler },
        { path: "packages/language-service/src/gen/builtins.ts", content: ls },
      ],
      process.argv.includes("--check"),
    ),
  );
}
