// Generates runtime/gen/opcodes.h and packages/dsdb/src/gen/opcodes.ts from contracts/opcodes.json (C2).
// Usage: node tools/gen-opcodes.ts [--check]
import { emit, readJson } from "./lib/gen.ts";

export interface OpcodeSpec {
  number: number;
  name: string;
  status: "stable" | "provisional" | "reserved";
  format: string;
  operands: string[];
  summary: string;
}

const HEADER = "Generated by tools/gen-opcodes.ts from contracts/opcodes.json. Do not edit.";

export function render(spec: { version: string; opcodes: OpcodeSpec[] }): { h: string; ts: string } {
  const ops = spec.opcodes;
  const w = Math.max(...ops.map((o) => o.name.length));
  const h = [
    `/* ${HEADER} */`,
    "#ifndef DSD_GEN_OPCODES_H",
    "#define DSD_GEN_OPCODES_H",
    "",
    `#define DSD_OPCODES_VERSION "${spec.version}"`,
    `#define DSD_OPCODE_COUNT ${ops.length}`,
    "",
    "/* Instruction word: op = bits 0-7, A = 8-15, B = 16-23, C = 24-31, Bx/sBx = 16-31. */",
    "#define DSD_OP(i) ((unsigned)(i) & 0xFFu)",
    "#define DSD_A(i) (((unsigned)(i) >> 8) & 0xFFu)",
    "#define DSD_B(i) (((unsigned)(i) >> 16) & 0xFFu)",
    "#define DSD_C(i) (((unsigned)(i) >> 24) & 0xFFu)",
    "#define DSD_BX(i) (((unsigned)(i) >> 16) & 0xFFFFu)",
    "#define DSD_SBX(i) ((int)(short)(((unsigned)(i) >> 16) & 0xFFFFu))",
    "",
    ...ops.map(
      (o) =>
        `#define DSD_OP_${o.name.padEnd(w)} ${String(o.number).padStart(3)} /* ${o.status}: ${o.operands.join(" ") || "-"} */`,
    ),
    "",
    "/* X-macro: X(name, number, stable) */",
    "#define DSD_OPCODE_LIST(X) \\",
    ...ops.map(
      (o, i) => `  X(${o.name}, ${o.number}, ${o.status === "stable" ? 1 : 0})${i < ops.length - 1 ? " \\" : ""}`,
    ),
    "",
    "#endif",
    "",
  ].join("\n");
  const ts = [
    `// ${HEADER}`,
    "",
    'export type OpcodeStatus = "stable" | "provisional" | "reserved";',
    "",
    "export interface OpcodeInfo {",
    "  readonly number: number;",
    "  readonly name: string;",
    "  readonly status: OpcodeStatus;",
    "  readonly format: string;",
    '  /** "field:kind", e.g. "A:reg", "Bx:k", "sBx:label". */',
    "  readonly operands: readonly string[];",
    "}",
    "",
    `export const OPCODES_VERSION = "${spec.version}";`,
    "",
    "export const OPCODES: readonly OpcodeInfo[] = [",
    ...ops.map(
      (o) =>
        `  { number: ${o.number}, name: "${o.name}", status: "${o.status}", format: "${o.format}", operands: [${o.operands.map((x) => `"${x}"`).join(", ")}] },`,
    ),
    "];",
    "",
  ].join("\n");
  return { h, ts };
}

if (import.meta.main) {
  const { h, ts } = render(readJson("contracts/opcodes.json"));
  process.exit(
    emit(
      "gen-opcodes",
      [
        { path: "runtime/gen/opcodes.h", content: h },
        { path: "packages/dsdb/src/gen/opcodes.ts", content: ts },
      ],
      process.argv.includes("--check"),
    ),
  );
}
